-- Generated by scripts/gen-solution-seed.ts from src/lib/product-catalog.ts. Do not edit by hand.
-- Bundled sample products: neutral sample owner, audience and outcome, validated maturity.

update public.products set
  audience = 'Geoscientists and reservoir engineers', outcome = 'Faster prospect evaluation from existing data',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222301' and owners = '[]'::jsonb;
update public.products set
  audience = 'Drilling and production engineers', outcome = 'Fewer non-productive hours on the rig',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222302' and owners = '[]'::jsonb;
update public.products set
  audience = 'Asset integrity teams', outcome = 'Earlier defect detection with less time on site',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222223' and owners = '[]'::jsonb;
update public.products set
  audience = 'Decommissioning and HSE teams', outcome = 'Lower abandonment cost and cleaner regulatory filings',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222303' and owners = '[]'::jsonb;
update public.products set
  audience = 'LNG plant operations', outcome = 'Higher train utilization and fewer missed cargoes',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222304' and owners = '[]'::jsonb;
update public.products set
  audience = 'Pipeline integrity engineers', outcome = 'Risk-ranked digs instead of calendar-based ones',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222305' and owners = '[]'::jsonb;
update public.products set
  audience = 'Terminal schedulers and commercial teams', outcome = 'Less demurrage and fewer scheduling conflicts',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222306' and owners = '[]'::jsonb;
update public.products set
  audience = 'Commercial and sustainability teams', outcome = 'Audit-ready carbon claims for low-carbon fuels',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222307' and owners = '[]'::jsonb;
update public.products set
  audience = 'Process and control engineers', outcome = 'Lower energy intensity per ton',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222308' and owners = '[]'::jsonb;
update public.products set
  audience = 'Control room and field operators', outcome = 'Faster onboarding and consistent operations',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222309' and owners = '[]'::jsonb;
update public.products set
  audience = 'Turnaround and maintenance managers', outcome = 'Turnarounds finished on schedule',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222310' and owners = '[]'::jsonb;
update public.products set
  audience = 'Quality and process engineers', outcome = 'Fewer off-spec batches and faster root cause',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222311' and owners = '[]'::jsonb;
update public.products set
  audience = 'Renewable operations and trading desks', outcome = 'Lower imbalance costs and better bids',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222312' and owners = '[]'::jsonb;
update public.products set
  audience = 'Grid operators and utility control rooms', outcome = 'Firm capacity from storage and fewer outages',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222221' and owners = '[]'::jsonb;
update public.products set
  audience = 'Asset managers and O&M contractors', outcome = 'Higher availability and fewer truck rolls',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222222' and owners = '[]'::jsonb;
update public.products set
  audience = 'Development and interconnection teams', outcome = 'Projects through the queue faster',
  owners = '[{"name":"Cloud Delivery samples","email":"","role":"Sample","team":"Bundled demo content"}]'::jsonb, tags = '{sample}',
  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()
where id = '22222222-2222-2222-2222-222222222313' and owners = '[]'::jsonb;
