/*
 * Generates db/seed/0005_product_catalog.sql from src/lib/product-catalog.ts:
 * products grouped by business line, one offering per product × delivery model with a published v1.0.0
 * architecture, and demo installs for existing customers. Repeatable: fixed ids and "on conflict do nothing".
 *
 *   bun scripts/gen-product-seed.ts
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";

import { toManifest } from "../src/lib/architecture";
import { monthlyEstimate, normalise, withDefaults } from "../src/lib/catalog";
import { BUSINESS_LINES, DELIVERY_MODELS, PRODUCTS } from "../src/lib/product-catalog";

const ORG = "11111111-1111-1111-1111-111111111111";
const uuid = (key: string) => {
  const h = createHash("md5").update(`cloud-delivery:${key}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
const REGIONS = ["eastus2", "centralus", "westeurope"];
const ENVS = ["development", "test", "production"];

const out: string[] = [
  "-- Generated by scripts/gen-product-seed.ts from src/lib/product-catalog.ts. Do not edit by hand.",
  "-- Products are the software services GridWorks sells, grouped by business line; offerings are each",
  "-- product delivered one way on Azure (Hosted, Customer Hosted, Enterprise Private, Regulated).",
  "",
];

for (const p of PRODUCTS) {
  const line = BUSINESS_LINES.find((l) => l.id === p.line)!;
  out.push(
    `insert into public.products (id, organization_id, name, description, category, status)`,
    `values (${q(p.id)}, ${q(ORG)}, ${q(p.name)}, ${q(p.pitch)}, ${q(line.name)}, 'active')`,
    `on conflict (id) do update set name = excluded.name, description = excluded.description, category = excluded.category;`,
  );
  if (p.adopts) {
    // The original demo offerings become this product's delivery models, keeping installs and releases.
    out.push(
      `update public.offerings set name = ${q(`${p.name} · `)} || name`,
      `where product_id = ${q(p.id)} and name not like ${q(`${p.name} · %`)};`,
    );
    continue;
  }
  for (const key of p.models) {
    const m = DELIVERY_MODELS[key];
    const topology = {
      landing: m.landing,
      landingZone: m.landingZone,
      publicAccess: false,
      privateEndpoints: true,
      regions: REGIONS,
      environments: ENVS,
    };
    const selected = normalise(
      [...p.services, ...m.extra, "monitoring", "key-vault"].map((id) => withDefaults(id)),
      topology,
    );
    const offeringName = `${p.name} · ${m.name}`;
    const offeringId = uuid(`offering:${offeringName}`);
    const versionId = uuid(`version:${offeringName}:1.0.0`);
    const monthly = monthlyEstimate(selected);
    const manifest = toManifest(
      slug(offeringName),
      "1.0.0",
      { selected, topology },
      {
        repository: "github.com/gridworks/cloud-delivery",
        path: `offerings/${slug(offeringName)}`,
        iac: "bicep",
        pipeline: "github-actions",
      },
    );
    out.push(
      `insert into public.offerings (id, product_id, name, description, offering_type, deployment_boundary, network_profile, supported_regions, estimated_monthly_cost_low, estimated_monthly_cost_high, status)`,
      `values (${q(offeringId)}, ${q(p.id)}, ${q(offeringName)}, ${q(m.body)}, '${m.offeringType}', 'subscription', '${m.networkProfile}', ${q(`{${REGIONS.join(",")}}`)}, ${monthly}, ${Math.round(monthly * 1.3)}, 'active')`,
      `on conflict (id) do nothing;`,
      `insert into public.offering_versions (id, offering_id, version, status, manifest_json, release_notes, published_at, created_by)`,
      `values (${q(versionId)}, ${q(offeringId)}, '1.0.0', 'published', ${j(manifest)}, ${q(`First release of ${p.name} as ${m.name}.`)}, now() - interval '60 days', 'Sarah Chen')`,
      `on conflict (id) do nothing;`,
    );
    for (const inst of p.installs.filter((i) => i.model === key))
      for (const [n, env] of inst.envs.entries()) {
        const envId = uuid(`env:${offeringName}:${inst.customer}:${env}`);
        const prod = env === "production";
        const cost = prod ? monthly : Math.round(monthly * 0.3);
        out.push(
          `insert into public.environments (id, customer_id, offering_id, desired_offering_version_id, actual_offering_version_id, name, environment_type, region, deployment_boundary, status, compliance_score, monthly_cost_estimate, configuration_json)`,
          `select ${q(envId)}, c.id, ${q(offeringId)}, ${q(versionId)}, ${q(versionId)}, '${prod ? "PROD" : "TEST"}', '${env}', ${q(REGIONS[n % 2]!)}, 'subscription', 'healthy', ${prod ? 98 : 100}, ${cost},`,
          `  ${j({ network: { mode: m.landing, privateEndpoints: true, publicAccess: false }, inputs: {}, overrides: {} })}`,
          `from public.customers c where c.customer_code = ${q(inst.customer)}`,
          `on conflict (id) do nothing;`,
          `insert into public.deployments (id, environment_id, deployment_type, desired_version, status, mode, requested_by, requested_at, started_at, completed_at)`,
          `select ${q(uuid(`dep:${envId}`))}, e.id, 'initial', '1.0.0', 'SUCCEEDED', 'demo', 'Mike Alvarez', now() - interval '${40 - n * 5} days', now() - interval '${40 - n * 5} days', now() - interval '${40 - n * 5} days' + interval '38 minutes'`,
          `from public.environments e where e.id = ${q(envId)}`,
          `on conflict (id) do nothing;`,
        );
      }
  }
}

writeFileSync("db/seed/0005_product_catalog.sql", `${out.join("\n")}\n`);
console.log(`wrote db/seed/0005_product_catalog.sql (${out.length} lines)`);
