/*
 * Generates db/seed/0007_solution_catalog.sql from src/lib/product-catalog.ts: gives the bundled sample
 * products their audience and outcome, marks them as sample content owned by no individual, and records
 * them as validated (each ships a published, architecture-reviewed offering). Only rows that have no
 * owners yet are touched, so real ownership is never overwritten.
 *
 *   bun scripts/gen-solution-seed.ts
 */
import { writeFileSync } from "node:fs";

import { PRODUCTS, SAMPLE_OWNER } from "../src/lib/product-catalog";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const out: string[] = [
  "-- Generated by scripts/gen-solution-seed.ts from src/lib/product-catalog.ts. Do not edit by hand.",
  "-- Bundled sample products: neutral sample owner, audience and outcome, validated maturity.",
  "",
];

for (const p of PRODUCTS)
  out.push(
    `update public.products set`,
    `  audience = ${q(p.audience)}, outcome = ${q(p.outcome)},`,
    `  owners = ${q(JSON.stringify([SAMPLE_OWNER]))}::jsonb, tags = '{sample}',`,
    `  maturity = 'validated', validated_at = now(), owner_confirmed_at = now(), updated_at = now()`,
    `where id = ${q(p.id)} and owners = '[]'::jsonb;`,
  );

writeFileSync("db/seed/0007_solution_catalog.sql", `${out.join("\n")}\n`);
console.log(`wrote db/seed/0007_solution_catalog.sql (${PRODUCTS.length} products)`);
