/*
 * A workload's design as documents to take away: a Markdown design document (requirements, services, where it
 * runs, the Well-Architected review, every flow, identities, private endpoints, cost) and a CSV of the
 * Well-Architected findings in the shape of a review export.
 */
import type { Architecture } from "../architecture";
import { SERVICE_BY_ID, inputsFor, monthlyEstimate } from "../catalog";
import { PILLARS, type Review } from "../waf";

import type { WorkloadFlow } from "./flows";

const LANDING: Record<string, string> = {
  "existing-customer-hub": "In the customer's Azure, peered to their existing landing zone hub",
  "dedicated-spoke": "In the customer's Azure, in its own network",
  "isv-hosted": "Hosted in your Azure",
};

const money = (n: number) => `$${Math.round(n).toLocaleString("en-US")}`;
const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

export function designDocument(
  name: string,
  arch: Architecture,
  review: Review,
  flows: WorkloadFlow[],
): string {
  const w = review.workload;
  const t = arch.topology;
  const byKind = (k: WorkloadFlow["kind"]) => flows.filter((f) => f.kind === k && f.available);
  const findings = review.findings.filter((f) => f.result === "fail" || f.result === "warn");
  const lines: string[] = [
    `# ${name}: architecture design`,
    "",
    `Generated by Cloud Delivery on ${new Date().toISOString().slice(0, 10)}. Every flow and finding below is computed from the design, not drawn by hand.`,
    "",
    "## Requirements",
    "",
    "| Requirement | Value |",
    "| --- | --- |",
    `| Criticality | ${w.criticality} |`,
    `| Availability target | ${w.slo}% |`,
    `| Recovery time / data loss | ${w.rtoMinutes} min / ${w.rpoMinutes} min |`,
    `| Data classification | ${w.data} |`,
    `| Audience | ${w.audience} |`,
    "",
    "## Where it runs",
    "",
    `- ${LANDING[t.landing] ?? t.landing}; placed in the **${t.landingZone}** landing zone.`,
    `- Regions: ${t.regions.join(", ")}. Environments: ${t.environments.join(", ")}.`,
    `- Public network access: ${t.publicAccess ? "allowed" : "disabled"}. Private endpoints for data services: ${t.privateEndpoints ? "yes" : "no"}.`,
    "",
    "## Services",
    "",
    "| Service | Settings | Azure resource |",
    "| --- | --- | --- |",
    ...arch.selected.map((s) => {
      const def = SERVICE_BY_ID.get(s.id);
      const settings = Object.entries(s.settings)
        .map(([k, v]) => `${k}: ${v}`)
        .join(", ");
      return `| ${cell(def?.name ?? s.id)} | ${cell(settings || "defaults")} | ${def?.resourceType ?? ""} |`;
    }),
    "",
    `Estimated list price: ${money(monthlyEstimate(arch.selected))} per production install per month, ${money(monthlyEstimate(arch.selected, "dev"))} per dev/test install.`,
    "",
    "## Well-Architected review",
    "",
    `Overall: **${review.overall ?? "–"}/100**`,
    "",
    "| Pillar | Score | Fail | Warn | Pass |",
    "| --- | --- | --- | --- | --- |",
    ...review.pillars.map(
      (p) =>
        `| ${PILLARS.find((x) => x.id === p.pillar)!.title} | ${p.score ?? "–"} | ${p.fail} | ${p.warn} | ${p.pass} |`,
    ),
    "",
    ...(findings.length
      ? [
          "### To address",
          "",
          ...findings.map(
            (f) =>
              `- **${f.result.toUpperCase()}** · ${PILLARS.find((x) => x.id === f.rec.pillar)!.short} · ${f.service ? (SERVICE_BY_ID.get(f.service)?.name ?? f.service) : "Workload"}: ${f.rec.title}. ${f.detail}${f.fix ? ` Fix: ${f.fix.label}.` : ""}${f.rec.learn ? ` ([Learn](${f.rec.learn}))` : ""}`,
          ),
          "",
        ]
      : ["Nothing failing or to warn about.", ""]),
  ];
  const section = (title: string, list: WorkloadFlow[]) => {
    if (!list.length) return;
    lines.push(`## ${title}`, "");
    list.forEach((f, i) => {
      lines.push(`${i + 1}. **${f.title}** — ${f.outcome?.text ?? f.summary}`);
      for (const s of f.steps)
        lines.push(
          `   - ${s.title}${s.via ? ` (${s.via})` : ""}${s.route ? `: ${s.route.text}` : ""}${s.gap ? ` — ${s.gap.severity === "fail" ? "gap" : "note"}: ${s.gap.text}` : ""}`,
        );
    });
    lines.push("");
  };
  section("Traffic flows", byKind("traffic"));
  section("Identity and access", byKind("identity"));
  section("Logging and telemetry", byKind("logging"));
  section("Deployment", byKind("deploy"));
  const inputs = inputsFor(arch.selected, t);
  if (inputs.length)
    lines.push(
      "## What each customer provides",
      "",
      ...inputs.map((i) => `- **${i.label}**: ${i.help}`),
      "",
    );
  return lines.join("\n");
}

/** The findings as CSV, in the shape of a Well-Architected Review export. */
export function findingsCsv(review: Review): string {
  const q = (s: string) => `"${s.replace(/"/g, '""')}"`;
  return [
    ["Pillar", "Service", "Recommendation", "Result", "Detail", "Fix", "Learn"].join(","),
    ...review.findings.map((f) =>
      [
        PILLARS.find((p) => p.id === f.rec.pillar)!.title,
        f.service ? (SERVICE_BY_ID.get(f.service)?.name ?? f.service) : "Workload",
        f.rec.title,
        f.result,
        f.detail,
        f.fix?.label ?? "",
        f.rec.learn ?? "",
      ]
        .map((x) => q(String(x)))
        .join(","),
    ),
  ].join("\n");
}
