/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as EstateRouteImport } from './routes/estate'
import { Route as OfferingsRouteImport } from './routes/offerings'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpgradesRouteImport } from './routes/upgrades'
import { Route as ConnectCustomerIdRouteImport } from './routes/connect.$customerId'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as DeliveryIndexRouteImport } from './routes/delivery.index'
import { Route as DeliveryUnitIdRouteImport } from './routes/delivery.$unitId'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments.index'
import { Route as DeploymentsDeploymentIdRouteImport } from './routes/deployments.$deploymentId'
import { Route as EngagementsIndexRouteImport } from './routes/engagements.index'
import { Route as EngagementsEngagementIdRouteImport } from './routes/engagements.$engagementId'
import { Route as FoundationsIndexRouteImport } from './routes/foundations.index'
import { Route as FoundationsFoundationIdRouteImport } from './routes/foundations.$foundationId'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as RecapEngagementIdRouteImport } from './routes/recap.$engagementId'
import { Route as WellArchitectedIndexRouteImport } from './routes/well-architected.index'
import { Route as WellArchitectedTopicRouteImport } from './routes/well-architected.$topic'
import { Route as FoundationsGuideIndexRouteImport } from './routes/foundations.guide.index'
import { Route as FoundationsGuideTopicRouteImport } from './routes/foundations.guide.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateRoute = EstateRouteImport.update({
  id: '/estate',
  path: '/estate',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsRoute = OfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradesRoute = UpgradesRouteImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectCustomerIdRoute = ConnectCustomerIdRouteImport.update({
  id: '/connect/$customerId',
  path: '/connect/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/delivery/',
  path: '/delivery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryUnitIdRoute = DeliveryUnitIdRouteImport.update({
  id: '/delivery/$unitId',
  path: '/delivery/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsDeploymentIdRoute = DeploymentsDeploymentIdRouteImport.update({
  id: '/deployments/$deploymentId',
  path: '/deployments/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsIndexRoute = EngagementsIndexRouteImport.update({
  id: '/engagements/',
  path: '/engagements/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsEngagementIdRoute = EngagementsEngagementIdRouteImport.update({
  id: '/engagements/$engagementId',
  path: '/engagements/$engagementId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsIndexRoute = FoundationsIndexRouteImport.update({
  id: '/foundations/',
  path: '/foundations/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsFoundationIdRoute = FoundationsFoundationIdRouteImport.update({
  id: '/foundations/$foundationId',
  path: '/foundations/$foundationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapEngagementIdRoute = RecapEngagementIdRouteImport.update({
  id: '/recap/$engagementId',
  path: '/recap/$engagementId',
  getParentRoute: () => rootRouteImport,
} as any)
const WellArchitectedIndexRoute = WellArchitectedIndexRouteImport.update({
  id: '/well-architected/',
  path: '/well-architected/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellArchitectedTopicRoute = WellArchitectedTopicRouteImport.update({
  id: '/well-architected/$topic',
  path: '/well-architected/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsGuideIndexRoute = FoundationsGuideIndexRouteImport.update({
  id: '/foundations/guide/',
  path: '/foundations/guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsGuideTopicRoute = FoundationsGuideTopicRouteImport.update({
  id: '/foundations/guide/$topic',
  path: '/foundations/guide/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/costs': typeof CostsRoute
  '/estate': typeof EstateRoute
  '/offerings': typeof OfferingsRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRoute
  '/upgrades': typeof UpgradesRoute
  '/connect/$customerId': typeof ConnectCustomerIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/delivery/$unitId': typeof DeliveryUnitIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/foundations/$foundationId': typeof FoundationsFoundationIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/recap/$engagementId': typeof RecapEngagementIdRoute
  '/well-architected/$topic': typeof WellArchitectedTopicRoute
  '/customers/': typeof CustomersIndexRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/engagements/': typeof EngagementsIndexRoute
  '/foundations/': typeof FoundationsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/well-architected/': typeof WellArchitectedIndexRoute
  '/foundations/guide/$topic': typeof FoundationsGuideTopicRoute
  '/foundations/guide/': typeof FoundationsGuideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/costs': typeof CostsRoute
  '/estate': typeof EstateRoute
  '/offerings': typeof OfferingsRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRoute
  '/upgrades': typeof UpgradesRoute
  '/connect/$customerId': typeof ConnectCustomerIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/delivery/$unitId': typeof DeliveryUnitIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/foundations/$foundationId': typeof FoundationsFoundationIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/recap/$engagementId': typeof RecapEngagementIdRoute
  '/well-architected/$topic': typeof WellArchitectedTopicRoute
  '/customers': typeof CustomersIndexRoute
  '/delivery': typeof DeliveryIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/engagements': typeof EngagementsIndexRoute
  '/foundations': typeof FoundationsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/well-architected': typeof WellArchitectedIndexRoute
  '/foundations/guide/$topic': typeof FoundationsGuideTopicRoute
  '/foundations/guide': typeof FoundationsGuideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/costs': typeof CostsRoute
  '/estate': typeof EstateRoute
  '/offerings': typeof OfferingsRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRoute
  '/upgrades': typeof UpgradesRoute
  '/connect/$customerId': typeof ConnectCustomerIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/delivery/$unitId': typeof DeliveryUnitIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/foundations/$foundationId': typeof FoundationsFoundationIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/recap/$engagementId': typeof RecapEngagementIdRoute
  '/well-architected/$topic': typeof WellArchitectedTopicRoute
  '/customers/': typeof CustomersIndexRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/engagements/': typeof EngagementsIndexRoute
  '/foundations/': typeof FoundationsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/well-architected/': typeof WellArchitectedIndexRoute
  '/foundations/guide/$topic': typeof FoundationsGuideTopicRoute
  '/foundations/guide/': typeof FoundationsGuideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/compliance'
    | '/costs'
    | '/estate'
    | '/offerings'
    | '/onboard'
    | '/settings'
    | '/upgrades'
    | '/connect/$customerId'
    | '/customers/$customerId'
    | '/delivery/$unitId'
    | '/deployments/$deploymentId'
    | '/engagements/$engagementId'
    | '/foundations/$foundationId'
    | '/products/$productId'
    | '/recap/$engagementId'
    | '/well-architected/$topic'
    | '/customers/'
    | '/delivery/'
    | '/deployments/'
    | '/engagements/'
    | '/foundations/'
    | '/products/'
    | '/well-architected/'
    | '/foundations/guide/$topic'
    | '/foundations/guide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/compliance'
    | '/costs'
    | '/estate'
    | '/offerings'
    | '/onboard'
    | '/settings'
    | '/upgrades'
    | '/connect/$customerId'
    | '/customers/$customerId'
    | '/delivery/$unitId'
    | '/deployments/$deploymentId'
    | '/engagements/$engagementId'
    | '/foundations/$foundationId'
    | '/products/$productId'
    | '/recap/$engagementId'
    | '/well-architected/$topic'
    | '/customers'
    | '/delivery'
    | '/deployments'
    | '/engagements'
    | '/foundations'
    | '/products'
    | '/well-architected'
    | '/foundations/guide/$topic'
    | '/foundations/guide'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/compliance'
    | '/costs'
    | '/estate'
    | '/offerings'
    | '/onboard'
    | '/settings'
    | '/upgrades'
    | '/connect/$customerId'
    | '/customers/$customerId'
    | '/delivery/$unitId'
    | '/deployments/$deploymentId'
    | '/engagements/$engagementId'
    | '/foundations/$foundationId'
    | '/products/$productId'
    | '/recap/$engagementId'
    | '/well-architected/$topic'
    | '/customers/'
    | '/delivery/'
    | '/deployments/'
    | '/engagements/'
    | '/foundations/'
    | '/products/'
    | '/well-architected/'
    | '/foundations/guide/$topic'
    | '/foundations/guide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ComplianceRoute: typeof ComplianceRoute
  CostsRoute: typeof CostsRoute
  EstateRoute: typeof EstateRoute
  OfferingsRoute: typeof OfferingsRoute
  OnboardRoute: typeof OnboardRoute
  SettingsRoute: typeof SettingsRoute
  UpgradesRoute: typeof UpgradesRoute
  ConnectCustomerIdRoute: typeof ConnectCustomerIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  DeliveryUnitIdRoute: typeof DeliveryUnitIdRoute
  DeploymentsDeploymentIdRoute: typeof DeploymentsDeploymentIdRoute
  EngagementsEngagementIdRoute: typeof EngagementsEngagementIdRoute
  FoundationsFoundationIdRoute: typeof FoundationsFoundationIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  RecapEngagementIdRoute: typeof RecapEngagementIdRoute
  WellArchitectedTopicRoute: typeof WellArchitectedTopicRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  EngagementsIndexRoute: typeof EngagementsIndexRoute
  FoundationsIndexRoute: typeof FoundationsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  WellArchitectedIndexRoute: typeof WellArchitectedIndexRoute
  FoundationsGuideTopicRoute: typeof FoundationsGuideTopicRoute
  FoundationsGuideIndexRoute: typeof FoundationsGuideIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate': {
      id: '/estate'
      path: '/estate'
      fullPath: '/estate'
      preLoaderRoute: typeof EstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings': {
      id: '/offerings'
      path: '/offerings'
      fullPath: '/offerings'
      preLoaderRoute: typeof OfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrades': {
      id: '/upgrades'
      path: '/upgrades'
      fullPath: '/upgrades'
      preLoaderRoute: typeof UpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$customerId': {
      id: '/connect/$customerId'
      path: '/connect/$customerId'
      fullPath: '/connect/$customerId'
      preLoaderRoute: typeof ConnectCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/delivery'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/$unitId': {
      id: '/delivery/$unitId'
      path: '/delivery/$unitId'
      fullPath: '/delivery/$unitId'
      preLoaderRoute: typeof DeliveryUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$deploymentId': {
      id: '/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof DeploymentsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements/': {
      id: '/engagements/'
      path: '/engagements'
      fullPath: '/engagements/'
      preLoaderRoute: typeof EngagementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements/$engagementId': {
      id: '/engagements/$engagementId'
      path: '/engagements/$engagementId'
      fullPath: '/engagements/$engagementId'
      preLoaderRoute: typeof EngagementsEngagementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/': {
      id: '/foundations/'
      path: '/foundations'
      fullPath: '/foundations/'
      preLoaderRoute: typeof FoundationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/$foundationId': {
      id: '/foundations/$foundationId'
      path: '/foundations/$foundationId'
      fullPath: '/foundations/$foundationId'
      preLoaderRoute: typeof FoundationsFoundationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$engagementId': {
      id: '/recap/$engagementId'
      path: '/recap/$engagementId'
      fullPath: '/recap/$engagementId'
      preLoaderRoute: typeof RecapEngagementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-architected/': {
      id: '/well-architected/'
      path: '/well-architected'
      fullPath: '/well-architected/'
      preLoaderRoute: typeof WellArchitectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-architected/$topic': {
      id: '/well-architected/$topic'
      path: '/well-architected/$topic'
      fullPath: '/well-architected/$topic'
      preLoaderRoute: typeof WellArchitectedTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/guide/': {
      id: '/foundations/guide/'
      path: '/foundations/guide'
      fullPath: '/foundations/guide/'
      preLoaderRoute: typeof FoundationsGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/guide/$topic': {
      id: '/foundations/guide/$topic'
      path: '/foundations/guide/$topic'
      fullPath: '/foundations/guide/$topic'
      preLoaderRoute: typeof FoundationsGuideTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ComplianceRoute: ComplianceRoute,
  CostsRoute: CostsRoute,
  EstateRoute: EstateRoute,
  OfferingsRoute: OfferingsRoute,
  OnboardRoute: OnboardRoute,
  SettingsRoute: SettingsRoute,
  UpgradesRoute: UpgradesRoute,
  ConnectCustomerIdRoute: ConnectCustomerIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  DeliveryUnitIdRoute: DeliveryUnitIdRoute,
  DeploymentsDeploymentIdRoute: DeploymentsDeploymentIdRoute,
  EngagementsEngagementIdRoute: EngagementsEngagementIdRoute,
  FoundationsFoundationIdRoute: FoundationsFoundationIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  RecapEngagementIdRoute: RecapEngagementIdRoute,
  WellArchitectedTopicRoute: WellArchitectedTopicRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  EngagementsIndexRoute: EngagementsIndexRoute,
  FoundationsIndexRoute: FoundationsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  WellArchitectedIndexRoute: WellArchitectedIndexRoute,
  FoundationsGuideTopicRoute: FoundationsGuideTopicRoute,
  FoundationsGuideIndexRoute: FoundationsGuideIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
