/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as EstateRouteImport } from './routes/estate'
import { Route as OfferingsRouteImport } from './routes/offerings'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpgradesRouteImport } from './routes/upgrades'
import { Route as ConnectCustomerIdRouteImport } from './routes/connect.$customerId'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments.index'
import { Route as DeploymentsDeploymentIdRouteImport } from './routes/deployments.$deploymentId'
import { Route as FoundationsIndexRouteImport } from './routes/foundations.index'
import { Route as FoundationsFoundationIdRouteImport } from './routes/foundations.$foundationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateRoute = EstateRouteImport.update({
  id: '/estate',
  path: '/estate',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsRoute = OfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradesRoute = UpgradesRouteImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectCustomerIdRoute = ConnectCustomerIdRouteImport.update({
  id: '/connect/$customerId',
  path: '/connect/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsDeploymentIdRoute = DeploymentsDeploymentIdRouteImport.update({
  id: '/deployments/$deploymentId',
  path: '/deployments/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsIndexRoute = FoundationsIndexRouteImport.update({
  id: '/foundations/',
  path: '/foundations/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsFoundationIdRoute = FoundationsFoundationIdRouteImport.update({
  id: '/foundations/$foundationId',
  path: '/foundations/$foundationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/costs': typeof CostsRoute
  '/estate': typeof EstateRoute
  '/offerings': typeof OfferingsRoute
  '/onboard': typeof OnboardRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/upgrades': typeof UpgradesRoute
  '/connect/$customerId': typeof ConnectCustomerIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/foundations/$foundationId': typeof FoundationsFoundationIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/foundations/': typeof FoundationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/costs': typeof CostsRoute
  '/estate': typeof EstateRoute
  '/offerings': typeof OfferingsRoute
  '/onboard': typeof OnboardRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/upgrades': typeof UpgradesRoute
  '/connect/$customerId': typeof ConnectCustomerIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/foundations/$foundationId': typeof FoundationsFoundationIdRoute
  '/customers': typeof CustomersIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/foundations': typeof FoundationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/costs': typeof CostsRoute
  '/estate': typeof EstateRoute
  '/offerings': typeof OfferingsRoute
  '/onboard': typeof OnboardRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/upgrades': typeof UpgradesRoute
  '/connect/$customerId': typeof ConnectCustomerIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/foundations/$foundationId': typeof FoundationsFoundationIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/foundations/': typeof FoundationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/compliance'
    | '/costs'
    | '/estate'
    | '/offerings'
    | '/onboard'
    | '/products'
    | '/settings'
    | '/upgrades'
    | '/connect/$customerId'
    | '/customers/$customerId'
    | '/deployments/$deploymentId'
    | '/foundations/$foundationId'
    | '/customers/'
    | '/deployments/'
    | '/foundations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/compliance'
    | '/costs'
    | '/estate'
    | '/offerings'
    | '/onboard'
    | '/products'
    | '/settings'
    | '/upgrades'
    | '/connect/$customerId'
    | '/customers/$customerId'
    | '/deployments/$deploymentId'
    | '/foundations/$foundationId'
    | '/customers'
    | '/deployments'
    | '/foundations'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/compliance'
    | '/costs'
    | '/estate'
    | '/offerings'
    | '/onboard'
    | '/products'
    | '/settings'
    | '/upgrades'
    | '/connect/$customerId'
    | '/customers/$customerId'
    | '/deployments/$deploymentId'
    | '/foundations/$foundationId'
    | '/customers/'
    | '/deployments/'
    | '/foundations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ComplianceRoute: typeof ComplianceRoute
  CostsRoute: typeof CostsRoute
  EstateRoute: typeof EstateRoute
  OfferingsRoute: typeof OfferingsRoute
  OnboardRoute: typeof OnboardRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  UpgradesRoute: typeof UpgradesRoute
  ConnectCustomerIdRoute: typeof ConnectCustomerIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  DeploymentsDeploymentIdRoute: typeof DeploymentsDeploymentIdRoute
  FoundationsFoundationIdRoute: typeof FoundationsFoundationIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  FoundationsIndexRoute: typeof FoundationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate': {
      id: '/estate'
      path: '/estate'
      fullPath: '/estate'
      preLoaderRoute: typeof EstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings': {
      id: '/offerings'
      path: '/offerings'
      fullPath: '/offerings'
      preLoaderRoute: typeof OfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrades': {
      id: '/upgrades'
      path: '/upgrades'
      fullPath: '/upgrades'
      preLoaderRoute: typeof UpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$customerId': {
      id: '/connect/$customerId'
      path: '/connect/$customerId'
      fullPath: '/connect/$customerId'
      preLoaderRoute: typeof ConnectCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$deploymentId': {
      id: '/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof DeploymentsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/': {
      id: '/foundations/'
      path: '/foundations'
      fullPath: '/foundations/'
      preLoaderRoute: typeof FoundationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/$foundationId': {
      id: '/foundations/$foundationId'
      path: '/foundations/$foundationId'
      fullPath: '/foundations/$foundationId'
      preLoaderRoute: typeof FoundationsFoundationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ComplianceRoute: ComplianceRoute,
  CostsRoute: CostsRoute,
  EstateRoute: EstateRoute,
  OfferingsRoute: OfferingsRoute,
  OnboardRoute: OnboardRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  UpgradesRoute: UpgradesRoute,
  ConnectCustomerIdRoute: ConnectCustomerIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  DeploymentsDeploymentIdRoute: DeploymentsDeploymentIdRoute,
  FoundationsFoundationIdRoute: FoundationsFoundationIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  FoundationsIndexRoute: FoundationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
